#pragma once
#include "Engine/YorkieEngine.h"
#include "Window/Window.h"
#include "GLFW/glfw3.h"

enum EKeyboardKeys
{
	KEY_A = GLFW_KEY_A,
	KEY_B = GLFW_KEY_B,
	KEY_C = GLFW_KEY_C,
	KEY_D = GLFW_KEY_D,
	KEY_E = GLFW_KEY_E,
	KEY_F = GLFW_KEY_F,
	KEY_G = GLFW_KEY_G,
	KEY_H = GLFW_KEY_H,
	KEY_I = GLFW_KEY_I,
	KEY_J = GLFW_KEY_J,
	KEY_K = GLFW_KEY_K,
	KEY_L = GLFW_KEY_L,
	KEY_M = GLFW_KEY_M,
	KEY_N = GLFW_KEY_N,
	//KEY_Ñ = GLFW_KEY_Ñ,
	KEY_O = GLFW_KEY_O,
	KEY_P = GLFW_KEY_P,
	KEY_Q = GLFW_KEY_Q,
	KEY_R = GLFW_KEY_R,
	KEY_S = GLFW_KEY_S,
	KEY_T = GLFW_KEY_T,
	KEY_U = GLFW_KEY_U,
	KEY_W = GLFW_KEY_W,
	KEY_X = GLFW_KEY_X,
	KEY_Y = GLFW_KEY_Y,
	KEY_Z = GLFW_KEY_Z,
	KEY_1 = GLFW_KEY_1,
	KEY_2 = GLFW_KEY_2,
	KEY_3 = GLFW_KEY_3,
	KEY_4 = GLFW_KEY_4,
	KEY_5 = GLFW_KEY_5,
	KEY_6 = GLFW_KEY_6,
	KEY_7 = GLFW_KEY_7,
	KEY_8 = GLFW_KEY_8,
	KEY_9 = GLFW_KEY_9,
	KEY_0 = GLFW_KEY_0,
	KEY_TAB = GLFW_KEY_TAB,
	KEY_LEFT_ALT = GLFW_KEY_LEFT_ALT,
	KEY_RIGHT_ALT = GLFW_KEY_RIGHT_ALT, 
	KEY_LEFT_CNTRL = GLFW_KEY_LEFT_CONTROL,
	KEY_RIGHT_CNTRL = GLFW_KEY_RIGHT_CONTROL,
	KEY_LEFT_SHIFT = GLFW_KEY_LEFT_SHIFT,
	KEY_RIGHT_SHIFT = GLFW_KEY_RIGHT_SHIFT
};

class YorkieAPI Controller
{
public:
	Controller(Window& window);
	bool IsKeyPressed(EKeyboardKeys KeyboardKey);

private: 
	Window* window;

};

